DROP TABLE IF EXISTS BOARD;

CREATE TABLE BOARD (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_writer VARCHAR(20) NOT NULL,
    board_pass VARCHAR(255),
    board_title VARCHAR(255),
    board_contents VARCHAR(255),
    board_hits INT
);