DROP TABLE IF EXISTS BOARD CASCADE;
CREATE TABLE BOARD (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    boardWriter VARCHAR(20) NOT NULL,
    boardPass VARCHAR(255),
    boardTitle VARCHAR(255),
    boardContents VARCHAR(255),
    boardHits INT
);
